<a href="https://colab.research.google.com/github/khan5125/PythonPractice/blob/main/final_sultion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd
import io

In [29]:
from google.colab import files
uploaded = files.upload()

Saving Assignment.xlsx to Assignment (1).xlsx


In [30]:
# read  both matrices from excel

for fn in uploaded.keys():
  if fn.endswith('.xlsx'):  # Assuming Excel file
    df = pd.read_excel(io.BytesIO(uploaded[fn]))
    # Assuming matrices are in the first two sheets
    try:
      source_matrix = df.iloc[:,:].values #read the entire sheet as numpy array
      # Access the second sheet (adjust sheet name if necessary)
      df2 = pd.read_excel(io.BytesIO(uploaded[fn]), sheet_name=1) # Specify sheet index or name
      model_matrix = df2.iloc[:,:].values
      print("Matrix 1:\n", source_matrix)
      print("\nMatrix 2:\n", model_matrix)

    except Exception as e:
      print(f"Error reading matrices from file {fn}: {e}")


Matrix 1:
 [[ 2 12 23 32]
 [45  3  0 34]
 [87 57 34 78]]

Matrix 2:
 [[ 3  8 23  4 12 17 32  9]
 [ 4  9 12  1 10 32  1  7]
 [21 45 97  9  0 21  9  6]
 [32  1 95  7  4  3  7  8]
 [ 1  3 83  6 19  8  6 32]
 [ 2  5 74  8 18  4  8 34]
 [ 4  0 64 12 26  1 34 78]]


In [31]:

# Get the dimensions of the matrices
source_rows, source_cols = source_matrix.shape
model_rows, model_cols = model_matrix.shape

# Initialize the result matrix with zeros
result_matrix = np.zeros((model_rows, model_cols))

# Iterate through the source matrix
for i in range(source_rows):
    for j in range(source_cols):
        # Get the current value from the source matrix
        source_value = source_matrix[i, j]

        # Iterate through the corresponding part of the model matrix
        for x in range(model_rows):
            for y in range(model_cols):
                # Handle cases where model_matrix sums to zero
                model_sum_at_ij = np.sum(model_matrix)
                if model_sum_at_ij == 0:
                    result_matrix[x,y] = 0
                else:
                  result_matrix[x, y] += source_value * (model_matrix[x,y] / model_sum_at_ij)

# Convert to pandas DataFrame for easy saving to Excel
result_df = pd.DataFrame(result_matrix)

# Save the result matrix to an Excel file
result_df.to_excel('result_matrix.xlsx', index=False, header=False)



In [35]:
# download result matrix

files.download('result_matrix.xlsx')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [36]:
from google.colab import files
uploaded = files.upload()

Saving result_matrix (4).xlsx to result_matrix (4).xlsx


In [37]:
# read  result matrix from excel

for fn in uploaded.keys():
  if fn.endswith('.xlsx'):  # Assuming Excel file
    df = pd.read_excel(io.BytesIO(uploaded[fn]))
    try:
      source_matrix = df.iloc[:,:].values #read the entire sheet as numpy array
      print("Result Matrix:\n", source_matrix)
    except Exception as e:
      print(f"Error reading matrices from file {fn}: {e}")


Result Matrix:
 [[ 1.50880445  3.39481001  4.52641335  0.37720111  3.77201112 12.07043559
   0.37720111  2.64040778]
 [ 7.92122335 16.97405005 36.58850788  3.39481001  0.          7.92122335
   3.39481001  2.26320667]
 [12.07043559  0.37720111 35.83410565  2.64040778  1.50880445  1.13160334
   2.64040778  3.0176089 ]
 [ 0.37720111  1.13160334 31.30769231  2.26320667  7.16682113  3.0176089
   2.26320667 12.07043559]
 [ 0.75440222  1.88600556 27.9128823   3.0176089   6.78962002  1.50880445
   3.0176089  12.82483781]
 [ 1.50880445  0.         24.14087118  4.52641335  9.80722892  0.37720111
  12.82483781 29.42168675]]


In [38]:
# Result_matrix is already defined from your previous code

# Convert to pandas DataFrame for easy manipulation
result_df = pd.DataFrame(result_matrix)

# Limit to two decimal places
result_df = result_df.round(2)

# Print the modified DataFrame
print("\nResult Matrix (Rounded to 2 decimal places):")
result_df


Result Matrix (Rounded to 2 decimal places):


0      1      2     3     4      5      6      7
0   1.13   3.02   8.68  1.51  4.53   6.41  12.07   3.39
1   1.51   3.39   4.53  0.38  3.77  12.07   0.38   2.64
2   7.92  16.97  36.59  3.39  0.00   7.92   3.39   2.26
3  12.07   0.38  35.83  2.64  1.51   1.13   2.64   3.02
4   0.38   1.13  31.31  2.26  7.17   3.02   2.26  12.07
5   0.75   1.89  27.91  3.02  6.79   1.51   3.02  12.82
6   1.51   0.00  24.14  4.53  9.81   0.38  12.82  29.42

In [39]:
print("\nResult Matrix (Rounded to 2 decimal places):\n", result_df.values)


Result Matrix (Rounded to 2 decimal places):
 [[ 1.13  3.02  8.68  1.51  4.53  6.41 12.07  3.39]
 [ 1.51  3.39  4.53  0.38  3.77 12.07  0.38  2.64]
 [ 7.92 16.97 36.59  3.39  0.    7.92  3.39  2.26]
 [12.07  0.38 35.83  2.64  1.51  1.13  2.64  3.02]
 [ 0.38  1.13 31.31  2.26  7.17  3.02  2.26 12.07]
 [ 0.75  1.89 27.91  3.02  6.79  1.51  3.02 12.82]
 [ 1.51  0.   24.14  4.53  9.81  0.38 12.82 29.42]]
